# Site settings
title: Android Kotlin 指南
email: your-email@domain.com
description: >
 在 Android 上使用 Kotlin 的官方手册（中译版）
baseurl: "/kotlin-guides"
url: "https://android.github.io"

# Build settings
markdown: kramdown

collections:
  - changes

plugins:
  - octopress-autoprefixer
  - jekyll-redirect-from

exclude:
  - vendor
